# Generated by Django 4.2.13 on 2024-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'booked_startDateTime', 'booked_endDateTime'), name='unique_appointment'),
        ),
    ]
