# Generated by Django 4.2.13 on 2024-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
