# Generated by Django 4.2.13 on 2024-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_appointment_booked_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_meetLink',
            field=models.CharField(default='', max_length=500),
        ),
    ]
